/* <orly/indy/context.cc>

   Implements <orly/indy/context.h>.

   Copyright 2010-2026 Atomic Kismet Company

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

#include <orly/indy/context.h>

#include <alloca.h>
#include <algorithm>
#include <limits>
#include <sstream>
#include <stdexcept>

#include <orly/indy/disk_layer.h>
#include <orly/indy/util/min_heap.h>
#include <orly/server/read_too_large.h>

#include <orly/rt/mutate.h>
#include <orly/var/mutation.h>
#include <orly/var/sabot_to_var.h>

using namespace std;
using namespace Base;
using namespace Orly;
using namespace Orly::Indy;

auto KeyCursorCollector = Fiber::MakeFiberLocal<TContext::TKeyCursorCollector>();

TContext::TContext(const Indy::L0::TManager::TPtr<TRepo> &private_repo, Atom::TCore::TExtensibleArena *arena)
    : TContextBase(arena), WalkerCount(0UL) {
  assert(KeyCursorCollector->KeyCursorCollection.IsEmpty());
  Indy::L0::TManager::TPtr<L0::TManager::TRepo> cur_repo = private_repo;
  RepoTree.push_back(make_pair(private_repo, make_unique<TRepo::TView>(private_repo)));
  for (;cur_repo->GetParentRepo(); cur_repo = *cur_repo->GetParentRepo()) {
    Indy::L0::TManager::TPtr<Indy::TRepo> parent = *cur_repo->GetParentRepo();
    RepoTree.push_back(make_pair(parent, make_unique<TRepo::TView>(parent)));
  }
}

TContext::~TContext() {
  assert(KeyCursorCollector->KeyCursorCollection.IsEmpty());
}

void TContext::ReleaseViews() {
  if (OpenCursorCount) {
    throw logic_error("TContext::ReleaseViews: a key cursor is still open on this context");
  }
  /* Each pair's view is destroyed before its repo pointer, so the view's Decr runs under a repo
     that is still pinned. */
  RepoTree.clear();
  ViewsReleased = true;
}

void TContext::CheckViewsHeld() const {
  if (ViewsReleased) [[unlikely]] {
    throw logic_error("TContext: read after the context's views were released");
  }
}

void TContext::SetReadBudget(size_t max_rows, size_t max_arena_bytes, const Atom::TSuprena *arena, size_t max_steps) {
  assert(arena || !max_arena_bytes);
  MaxRows = max_rows ? max_rows : Unlimited;
  MaxArenaBytes = max_arena_bytes ? max_arena_bytes : Unlimited;
  BudgetArena = arena;
  InFlightScope.reset();
  InFlightBudget.SetLimits(max_steps, max_arena_bytes);
  if (max_steps || max_arena_bytes) {
    InFlightScope.emplace(&InFlightBudget);
  }
}

void TContext::CheckArenaBudget() const {
  if (MaxArenaBytes != Unlimited && BudgetArena->GetByteSize() > MaxArenaBytes) {
    OnOverBudget();
  }
}

void TContext::OnOverBudget() const {
  std::ostringstream msg;
  msg << "read too large: ";
  if (RowsWalked > MaxRows) {
    msg << "it walked more than " << MaxRows << " rows (--read_budget_rows)";
  } else {
    msg << "it used more than " << MaxArenaBytes << " bytes of result memory (--read_budget_mb)";
  }
  msg << "; retrying won't help, read a narrower range or raise the budget";
  throw Server::TReadTooLarge(msg.str());
}

Indy::TKey TContext::operator[](const Indy::TIndexKey &index_key) {
  /* check to see if any of our current key cursors are on this key.
     We're doing this as a quick fix to the fact that we've lost which cursor (if any) this key
     originated from in the code gen. (loss of information). */
  const auto &key = index_key.GetKey();
  for (TKeyCursorCollection::TCursor csr(&KeyCursorCollector->KeyCursorCollection); csr; ++csr) {
    const Indy::TPresentWalker::TItem &cur_item = csr->GetVal();
    if (Indy::TKey::EqEq(cur_item.Key, cur_item.KeyArena, key.GetCore(), key.GetArena())) {
      /* we found a cursor that is on the key we're looking for. let's just return the result. */
      return Indy::TKey(cur_item.Op, cur_item.OpArena);
    }
  }
  /* no dice. we're going to have to make a new walker. This suggests someone is reading an explicit
     key (as opposed to one generated by the "keys" expression), or we've manipulated / collected keys
     to the point where the cursor has advanced past what we're trying to read. */
  ++WalkerCount;
  TPresentWalker walker(this, RepoTree, index_key, /* exact_point */ true);
  if (!walker) {
    /* A hit was charged by the walker; a miss is still a lookup (#694). */
    ChargeRow();
  }
  if (walker) {
    const Indy::TPresentWalker::TItem &item = *walker;
    return Indy::TKey(Atom::TCore(GetArena(), alloca(Sabot::State::GetMaxStateSize()), item.OpArena, item.Op), GetArena());
  }
  /* We return an empty var here because in the case of an optional type being returned, the result is "empty" not a throw.
     A wrapper promotes empty -> throw if we need to end up as not an optional. */
  return Indy::TKey(Atom::TCore(), nullptr);
}

bool TContext::Exists(const Indy::TIndexKey &key) {
  ++WalkerCount;
  TPresentWalker walker(this, RepoTree, key, /* exact_point */ true);
  if (!walker) {
    ChargeRow();
  }
  return static_cast<bool>(walker);
}

int64_t TContext::CountKeys(const Indy::TIndexKey &pattern) {
  ++WalkerCount;
  if (const auto count = TryCountByRank(pattern, nullptr)) {
    return *count;
  }
  TPresentWalker walker(this, RepoTree, pattern, /* exact_point */ false, /* keys_only */ true);
  return CountKeys(walker);
}

int64_t TContext::CountKeys(const Indy::TIndexKey &from, const Indy::TIndexKey &to) {
  if (from.GetIndexId() != to.GetIndexId()) {
    throw std::invalid_argument("key range endpoints must belong to one index");
  }
  ++WalkerCount;
  if (const auto count = TryCountByRank(from, &to)) {
    return *count;
  }
  TPresentWalker walker(this, RepoTree, from, to, /* keys_only */ true);
  return CountKeys(walker);
}

int64_t TContext::CountKeys(TPresentWalker &walker) {
  CheckArenaBudget();
  int64_t count = 0;
  for (; walker; ++walker) {
    if (count == std::numeric_limits<int64_t>::max()) {
      throw std::overflow_error("key count exceeds int range");
    }
    ++count;
  }
  return count;
}

void TContext::ChargeRows(size_t n) {
  if (!n) {
    return;
  }
  if (MaxRows != Unlimited && n > MaxRows - std::min(RowsWalked, MaxRows)) [[unlikely]] {
    /* One at a time, the walk would have stopped on the first row past the limit. */
    RowsWalked = std::max(RowsWalked + 1UL, MaxRows + 1UL);
    OnOverBudget();
  }
  RowsWalked += n;
  if (MaxArenaBytes != Unlimited && BudgetArena->GetByteSize() > MaxArenaBytes) [[unlikely]] {
    OnOverBudget();
  }
}

namespace {

  /* True iff the key is a tuple of defined members of scalar type followed only by free ones,
     so the keys of one index it matches (all of one arity) are one run of the index's order. */
  bool IsRankable(const Indy::TKey &key) {
    const Atom::TCore &core = key.GetCore();
    if (!core.IsTuple()) {
      return false;
    }
    const Atom::TCore::TOffset *const off = core.TryGetOffset();
    const uint32_t *const elem_count = core.TryGetElemCount();
    if (!off || !elem_count) {
      return false;
    }
    void *pin_alloc = alloca(sizeof(Atom::TCore::TArena::TFinalPin));
    Atom::TCore::TArena::TFinalPin::TWrapper pin(key.GetArena()->Pin(*off, sizeof(Atom::TCore::TNote) + (sizeof(Atom::TCore) * *elem_count), pin_alloc));
    const Atom::TCore *member, *limit;
    pin->GetNote()->Get(member, limit);
    bool free_seen = false;
    for (; member < limit; ++member) {
      if (member->IsFree()) {
        free_seen = true;
      } else if (free_seen || member->TryGetElemCount()) {
        return false;
      }
    }
    return true;
  }

  /* True iff every entry of the layer lies inside the view's window, so the repo's walk would
     filter none of them out. */
  bool IsWhollyVisible(const Indy::L0::TManager::TRepo::TDataLayer *layer, const TRepo::TView &view) {
    return layer->GetLowestSeq() >= *view.GetLower() && layer->GetHighestSeq() <= *view.GetUpper();
  }

}  // namespace

std::optional<int64_t> TContext::TryCountByRank(const Indy::TIndexKey &from, const Indy::TIndexKey *to) {
  CheckViewsHeld();
  if (!RankCounts || !IsRankable(to ? to->GetKey() : from.GetKey())) {
    return std::nullopt;
  }
  using TDataLayer = Indy::L0::TManager::TRepo::TDataLayer;
  /* Leave the count to the walk unless some disk file can be ranked, so a count over memory
     layers alone costs nothing more than before. */
  bool any_ranked = false;
  for (const auto &[repo, view] : RepoTree) {
    if (view->GetLower() && view->GetUpper()) {
      view->ForEachLayer([&](const TDataLayer *layer) {
        any_ranked = any_ranked || (layer->GetKind() == TDataLayer::Disk && IsWhollyVisible(layer, *view));
      });
    }
  }
  if (!any_ranked) {
    return std::nullopt;
  }
  CheckArenaBudget();
  /* The same walkers the repos' walks would build, one per layer of each repo, merged here in
     one heap rather than a heap per repo. A key's first entry in the merge decides whether it
     counts, just as in TPresentWalker: the repo nearest the POV first, then, within a repo,
     the newest. */
  struct TSource {
    std::unique_ptr<Indy::TPresentWalker> Walker;
    /* The walker as a disk file walker when its whole file is visible, so it can be ranked. */
    Disk::TPresentWalkFileWrapper *File = nullptr;
    const TDiskLayer *Layer = nullptr;
    std::shared_ptr<const Disk::TTombstoneCounts> Counts;
    size_t RepoPos;
    /* The repo's window. A walker that can't be ranked skips the entries outside it, as the
       repo's walk does. */
    TSequenceNumber Lower, Upper;
  };
  std::vector<TSource> sources;
  for (size_t repo_pos = 0UL; repo_pos < RepoTree.size(); ++repo_pos) {
    const auto &view = RepoTree[repo_pos].second;
    if (!view->GetLower() || !view->GetUpper()) {
      continue;
    }
    const auto add = [&](const TDataLayer *layer) {
      TSource source;
      source.Walker = to ? layer->NewPresentWalker(from, *to) : layer->NewPresentWalker(from, /* exact_point */ false);
      if (layer->GetKind() == TDataLayer::Disk && IsWhollyVisible(layer, *view)) {
        source.File = dynamic_cast<Disk::TPresentWalkFileWrapper *>(source.Walker.get());
        source.Layer = static_cast<const TDiskLayer *>(layer);
      }
      source.RepoPos = repo_pos;
      source.Lower = *view->GetLower();
      source.Upper = *view->GetUpper();
      sources.push_back(std::move(source));
    };
    view->ForEachLayer(add);
  }
  const auto settle = [](TSource &source) {
    if (!source.File) {
      for (Indy::TPresentWalker &walker = *source.Walker;
           walker && ((*walker).SequenceNumber < source.Lower || (*walker).SequenceNumber > source.Upper); ++walker) {}
    }
  };
  struct TOrder {
    const std::vector<TSource> *Sources;
    bool operator()(const Indy::TPresentWalker::TItem &lhs, size_t lhs_pos, const Indy::TPresentWalker::TItem &rhs, size_t rhs_pos) const {
      const Atom::TComparison comp = lhs.CompareKeys(rhs);
      if (!Atom::IsEq(comp)) {
        return Atom::IsLt(comp);
      }
      const size_t lhs_repo = (*Sources)[lhs_pos].RepoPos, rhs_repo = (*Sources)[rhs_pos].RepoPos;
      return lhs_repo < rhs_repo || (lhs_repo == rhs_repo && lhs.SequenceNumber >= rhs.SequenceNumber);
    }
  };
  Util::TMinHeap<Indy::TPresentWalker::TItem, size_t, TOrder> heap(sources.size() + 1UL, TOrder{&sources});
  for (size_t pos = 0UL; pos < sources.size(); ++pos) {
    settle(sources[pos]);
    if (*sources[pos].Walker) {
      heap.Insert(**sources[pos].Walker, pos);
    }
  }
  int64_t count = 0;
  const auto add_to_count = [&](size_t n) {
    ChargeRows(n);
    if (n > static_cast<size_t>(std::numeric_limits<int64_t>::max() - count)) {
      throw std::overflow_error("key count exceeds int range");
    }
    count += static_cast<int64_t>(n);
  };
  std::vector<size_t> holders;
  while (heap) {
    size_t pos;
    const Indy::TPresentWalker::TItem top = heap.Pop(pos);
    TSource &source = sources[pos];
    size_t next_pos;
    const bool alone = !heap || !Atom::IsEq(heap.Peek(next_pos).CompareKeys(top));
    if (alone && source.File) {
      /* No other layer of any repo holds a key from this one up to the next key in the merge,
         so this file alone decides every key in that stretch. */
      if (!source.Counts) {
        source.Counts = source.Layer->GetTombstoneCounts(from.GetIndexId(), source.File->GetNumRanks());
      }
      const auto [keys, tombstones] = source.File->SkipBelow(heap ? &heap.Peek(next_pos) : nullptr, *source.Counts);
      assert(tombstones <= keys);
      RowsCountedByRank += keys - tombstones;
      add_to_count(keys - tombstones);
      if (*source.Walker) {
        heap.Insert(**source.Walker, pos);
      }
      continue;
    }
    /* The key's first entry decides it. Move every layer holding it past it. */
    if (!top.Op.IsTombstone()) {
      add_to_count(1UL);
    }
    holders.clear();
    holders.push_back(pos);
    while (heap && Atom::IsEq(heap.Peek(next_pos).CompareKeys(top))) {
      heap.Pop(next_pos);
      holders.push_back(next_pos);
    }
    for (size_t holder : holders) {
      TSource &held = sources[holder];
      Indy::TPresentWalker &walker = *held.Walker;
      if (held.File) {
        held.File->NextKey();
      } else {
        do {
          ++walker;
        } while (walker && Atom::IsEq((*walker).CompareKeys(top)));
        settle(held);
      }
      if (walker) {
        heap.Insert(*walker, holder);
      }
    }
  }
  return count;
}

TContext::TPresentWalker::TPresentWalker(TContext *ctx, const TRepoTree &repo_tree, const TIndexKey &key,
                                        bool exact_point, bool keys_only)
    : MinHeap(repo_tree.size()),
      Valid(false),
      KeysOnly(keys_only),
      FoldArena(ctx->GetArena()),
      FoldDedupProbes(&ctx->FoldDedupProbes),
      Context(ctx) {
  ctx->CheckViewsHeld();
  assert(Fiber::TFrame::LocalFramePool);
  size_t pos = 0;
  ctx->PresentWalkConsTimer.Start();
  //printf("TPresentWalker()\n");
  for (const auto &iter : repo_tree) {
    //printf("TPresentWalker() push back repo walker\n");
    WalkerVec.emplace_back(iter.first->NewPresentWalker(iter.second, key, /* ignore_tombstone */ false, exact_point));
    //Indy::TPresentWalker &walker = *WalkerVec.back();
  }
  for (auto &walker_ptr : WalkerVec) {
    Indy::TPresentWalker &walker = *walker_ptr;
    if (walker) {
      MinHeap.Insert(*walker, pos);
    }
    ++pos;
  }
  Valid = static_cast<bool>(MinHeap);
  Refresh();
  ctx->PresentWalkConsTimer.Stop();
}

TContext::TPresentWalker::TPresentWalker(TContext *ctx, const TRepoTree &repo_tree, const TIndexKey &from,
                                        const TIndexKey &to, bool keys_only)
    : MinHeap(repo_tree.size()),
      Valid(false),
      KeysOnly(keys_only),
      FoldArena(ctx->GetArena()),
      FoldDedupProbes(&ctx->FoldDedupProbes),
      Context(ctx) {
  ctx->CheckViewsHeld();
  ctx->PresentWalkConsTimer.Start();
  size_t pos = 0;
  for (const auto &iter : repo_tree) {
    WalkerVec.emplace_back(iter.first->NewPresentWalker(iter.second, from, to, false));
    Indy::TPresentWalker &walker = *WalkerVec.back();
    if (walker) {
      MinHeap.Insert(*walker, pos);
    }
    ++pos;
  }
  Valid = static_cast<bool>(MinHeap);
  Refresh();
  ctx->PresentWalkConsTimer.Stop();
}

TContext::TPresentWalker::~TPresentWalker() {}

void TContext::TPresentWalker::Refresh() {
  bool done = false;
  size_t pos;
  while (Valid) {
    const Indy::TPresentWalker::TItem &cur_item = MinHeap.Pop(pos);
    Indy::TPresentWalker &walker = *WalkerVec[pos];
    assert((*walker).KeyArena == cur_item.KeyArena);
    assert((*walker).OpArena == cur_item.OpArena);
    assert((*walker).SequenceNumber == cur_item.SequenceNumber);
    if (Item.KeyArena == nullptr || (Indy::TKey::TupleNeEq(Item.Key, Item.KeyArena, cur_item.Key, cur_item.KeyArena))) {
      Item = cur_item;
      if (!Item.Op.IsTombstone()) {
        done = true;
      }
    }
    ++walker;
    if (walker) {
      MinHeap.Insert(*walker, pos);
    }
    if (!done) {
      Valid = static_cast<bool>(MinHeap);
    } else {
      /* Phase 3 of #49: if the anchor entry was produced by a defer-safe
         commutative mutator, fold older same-mutator entries (and the
         eventual Assign base) into a single resolved value before
         returning. No-op when the anchor is an Assign. */
      if (Var::IsDeferSafeCommutative(Item.Mutator) && !KeysOnly) {
        ApplyDeferredFold();
      }
      /* One row for the read budget (#694). */
      Context->ChargeRow();
      break;
    }
  }
}

void TContext::TPresentWalker::ApplyDeferredFold() {
  /* Walk back through additional heap entries on the same key, folding
     them via Rt::Mutate. The loop terminates on:
       * Heap empty -- accumulated value stands (no Assign base existed;
         the commutative-mutator identity is "missing", matching the
         existing "first += against an empty key" semantics).
       * Different key -- next call to Refresh handles that key.
       * Tombstone on this key -- history below the tombstone is
         invisible; accumulated value stands.
       * Same key + Assign -- the base. Fold the accumulator onto it.
       * Same key + a different mutator -- mixed-mutator history, which
         TMutation::Augment already rejects at compose time. We surface
         the accumulator as-is and let downstream typed code react.

     Dedup: the SAME logical update can appear in two repos briefly
     during a Tetris push-to-parent / pop-from-child window. Both copies
     have the same UpdateId (the per-transaction TUuid from session.cc)
     but different per-repo SeqNums. We track seen UpdateIds and skip
     duplicates -- without this, the Wikipedia-pageviews demo's Go
     driver (which hammers tighter than the Python one) reproducibly
     double-counted ~1 per ~5,000 increments under contention. Entries
     with a zero UpdateId (e.g. the disk walker, which never hits the
     cross-repo Tetris window) are passed through without dedup. */
  const TMutator mut = Item.Mutator;
  void *state_alloc_a = alloca(Sabot::State::GetMaxStateSize() * 3);
  void *state_alloc_b = static_cast<uint8_t *>(state_alloc_a) + Sabot::State::GetMaxStateSize();
  void *state_alloc_c = static_cast<uint8_t *>(state_alloc_b) + Sabot::State::GetMaxStateSize();
  Var::TVar acc = Var::ToVar(*Sabot::State::TAny::TWrapper(Item.Op.NewState(Item.OpArena, state_alloc_a)));
  const Base::TUuid zero_uuid;
  /* A hash set, so a key with W unmerged entries folds in O(W) rather than
     the O(W^2) a linear scan of the ids seen so far cost (#696). Its hash
     and equality count themselves into the context's stats. */
  struct TCountingHash {
    size_t *Probes;
    size_t operator()(const Base::TUuid &id) const {
      ++*Probes;
      return std::hash<Base::TUuid>()(id);
    }
  };
  struct TCountingEq {
    size_t *Probes;
    bool operator()(const Base::TUuid &lhs, const Base::TUuid &rhs) const {
      ++*Probes;
      return lhs == rhs;
    }
  };
  std::unordered_set<Base::TUuid, TCountingHash, TCountingEq> seen_update_ids(
      0, TCountingHash{FoldDedupProbes}, TCountingEq{FoldDedupProbes});
  if (Item.UpdateId != zero_uuid) {
    seen_update_ids.insert(Item.UpdateId);
  }

  while (MinHeap) {
    size_t peek_pos;
    const Indy::TPresentWalker::TItem &peek = MinHeap.Peek(peek_pos);
    if (Indy::TKey::TupleNeEq(Item.Key, Item.KeyArena, peek.Key, peek.KeyArena)) {
      break;
    }
    if (peek.Op.IsTombstone()) {
      break;
    }
    if (peek.Mutator != TMutator::Assign && peek.Mutator != mut) {
      break;
    }
    /* Commit to consuming this item. Copy the bits we need before Pop
       invalidates the underlying walker's Item slot. */
    const TMutator peek_mut = peek.Mutator;
    const Atom::TCore peek_op = peek.Op;
    Atom::TCore::TArena *const peek_op_arena = peek.OpArena;
    const Base::TUuid peek_update_id = peek.UpdateId;

    size_t consumed_pos;
    MinHeap.Pop(consumed_pos);

    /* Advance + reinsert the walker we just popped from regardless of
       whether we fold this entry. */
    Indy::TPresentWalker &consumed_walker = *WalkerVec[consumed_pos];
    ++consumed_walker;
    if (consumed_walker) {
      MinHeap.Insert(*consumed_walker, consumed_pos);
    }

    /* Dedup by UpdateId. If we've already consumed this logical
       update from another repo's walker in the same fold, drop it. */
    if (peek_update_id != zero_uuid && !seen_update_ids.insert(peek_update_id).second) {
      continue;
    }

    Var::TVar peek_val = Var::ToVar(*Sabot::State::TAny::TWrapper(peek_op.NewState(peek_op_arena, state_alloc_b)));
    if (peek_mut == TMutator::Assign) {
      /* Base. acc represents the accumulated RHS; result is base OP acc. */
      acc = Rt::Mutate(peek_val, mut, acc);
    } else {
      /* Same commutative mutator. */
      acc = Rt::Mutate(acc, mut, peek_val);
    }

    if (peek_mut == TMutator::Assign) {
      break;
    }
  }

  /* Stuff the resolved value back into Item.Op via FoldArena (owned by
     the enclosing TContext, so the TCore outlives this walker). Tag it
     as Assign so downstream consumers don't re-attempt the fold. */
  Item.Op = Atom::TCore(FoldArena, Sabot::State::TAny::TWrapper(Var::NewSabot(state_alloc_c, acc)).get());
  Item.OpArena = FoldArena;
  Item.Mutator = TMutator::Assign;
}

TContext::TKeyCursor::TKeyCursor(TContext *context, const Indy::TIndexKey &pattern)
    : Orly::TKeyCursor(context->Arena),
      Key(pattern),
      Valid(true),
      Cached(false),
      Csr(context, context->RepoTree, Key),
      ContextMembership(this),
      Owner(context) {
  ++(context->WalkerCount);
  ++(context->OpenCursorCount);
}

TContext::TKeyCursor::TKeyCursor(TContext *context, const Indy::TIndexKey &from, const Indy::TIndexKey &to)
    : Orly::TKeyCursor(context->Arena),
      Key(from),
      To(to),
      Valid(true),
      Cached(false),
      Csr(context, context->RepoTree, Key, To),
      ContextMembership(this),
      Owner(context) {
  ++(context->WalkerCount);
  ++(context->OpenCursorCount);
}

TContext::TKeyCursor::~TKeyCursor() {
  ContextMembership.Remove();
  assert(Owner->OpenCursorCount);
  --(Owner->OpenCursorCount);
}

TContext::TKeyCursor::operator bool() const {
  Refresh();
  return Valid;
}

const Indy::TKey &TContext::TKeyCursor::operator*() const {
  Refresh();
  assert(Valid);
  assert(Cached);
  return Item;
}

const Indy::TKey *TContext::TKeyCursor::operator->() const {
  Refresh();
  assert(Valid);
  assert(Cached);
  return &Item;
}

TContext::TKeyCursor &TContext::TKeyCursor::operator++() {
  assert(Valid);
  Cached = false;
  ++Csr;
  ContextMembership.Remove();
  Refresh();
  return *this;
}

const TContext::TPresentWalker::TItem &TContext::TKeyCursor::GetVal() const {
  assert(Valid);
  assert(Csr);
  return *Csr;
}

void TContext::TKeyCursor::Refresh() const {
  if (Valid && !Cached) {
    Cached = true;
    if (Csr) {
      Item = Indy::TKey((*Csr).Key, (*Csr).KeyArena);
      /* insert ourselves into the thread local key cursor collection */
      ContextMembership.Insert(&(KeyCursorCollector->KeyCursorCollection));
    } else {
      Valid = false;
    }
  }
}