/* <orly/indy/context.cc>

   Implements <orly/indy/context.h>.

   Copyright 2010-2026 Atomic Kismet Company

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

#include <orly/indy/context.h>

#include <orly/rt/mutate.h>
#include <orly/var/mutation.h>
#include <orly/var/sabot_to_var.h>

using namespace std;
using namespace Base;
using namespace Orly;
using namespace Orly::Indy;

auto KeyCursorCollector = Fiber::MakeFiberLocal<TContext::TKeyCursorCollector>();

TContext::TContext(const Indy::L0::TManager::TPtr<TRepo> &private_repo, Atom::TCore::TExtensibleArena *arena)
    : TContextBase(arena), WalkerCount(0UL) {
  assert(KeyCursorCollector->KeyCursorCollection.IsEmpty());
  Indy::L0::TManager::TPtr<L0::TManager::TRepo> cur_repo = private_repo;
  RepoTree.push_back(make_pair(private_repo, make_unique<TRepo::TView>(private_repo)));
  for (;cur_repo->GetParentRepo(); cur_repo = *cur_repo->GetParentRepo()) {
    Indy::L0::TManager::TPtr<Indy::TRepo> parent = *cur_repo->GetParentRepo();
    RepoTree.push_back(make_pair(parent, make_unique<TRepo::TView>(parent)));
  }
}

TContext::~TContext() {
  assert(KeyCursorCollector->KeyCursorCollection.IsEmpty());
}

Indy::TKey TContext::operator[](const Indy::TIndexKey &index_key) {
  /* check to see if any of our current key cursors are on this key.
     We're doing this as a quick fix to the fact that we've lost which cursor (if any) this key
     originated from in the code gen. (loss of information). */
  const auto &key = index_key.GetKey();
  for (TKeyCursorCollection::TCursor csr(&KeyCursorCollector->KeyCursorCollection); csr; ++csr) {
    const Indy::TPresentWalker::TItem &cur_item = csr->GetVal();
    if (Indy::TKey::EqEq(cur_item.Key, cur_item.KeyArena, key.GetCore(), key.GetArena())) {
      /* we found a cursor that is on the key we're looking for. let's just return the result. */
      return Indy::TKey(cur_item.Op, cur_item.OpArena);
    }
  }
  /* no dice. we're going to have to make a new walker. This suggests someone is reading an explicit
     key (as opposed to one generated by the "keys" expression), or we've manipulated / collected keys
     to the point where the cursor has advanced past what we're trying to read. */
  ++WalkerCount;
  TPresentWalker walker(this, RepoTree, index_key, /* exact_point */ true);
  if (walker) {
    const Indy::TPresentWalker::TItem &item = *walker;
    return Indy::TKey(Atom::TCore(GetArena(), alloca(Sabot::State::GetMaxStateSize()), item.OpArena, item.Op), GetArena());
  }
  /* We return an empty var here because in the case of an optional type being returned, the result is "empty" not a throw.
     A wrapper promotes empty -> throw if we need to end up as not an optional. */
  return Indy::TKey(Atom::TCore(), nullptr);
}

bool TContext::Exists(const Indy::TIndexKey &key) {
  ++WalkerCount;
  TPresentWalker walker(this, RepoTree, key, /* exact_point */ true);
  return static_cast<bool>(walker);
}

TContext::TPresentWalker::TPresentWalker(TContext *ctx, const TRepoTree &repo_tree, const TIndexKey &key, bool exact_point)
    : MinHeap(repo_tree.size()),
      Valid(false),
      FoldArena(ctx->GetArena()) {
  assert(Fiber::TFrame::LocalFramePool);
  size_t pos = 0;
  ctx->PresentWalkConsTimer.Start();
  //printf("TPresentWalker()\n");
  for (const auto &iter : repo_tree) {
    //printf("TPresentWalker() push back repo walker\n");
    WalkerVec.emplace_back(iter.first->NewPresentWalker(iter.second, key, /* ignore_tombstone */ false, exact_point));
    //Indy::TPresentWalker &walker = *WalkerVec.back();
  }
  for (auto &walker_ptr : WalkerVec) {
    Indy::TPresentWalker &walker = *walker_ptr;
    if (walker) {
      MinHeap.Insert(*walker, pos);
    }
    ++pos;
  }
  Valid = static_cast<bool>(MinHeap);
  Refresh();
  ctx->PresentWalkConsTimer.Stop();
}

TContext::TPresentWalker::TPresentWalker(TContext *ctx, const TRepoTree &repo_tree, const TIndexKey &from, const TIndexKey &to)
    : MinHeap(repo_tree.size()),
      Valid(false),
      FoldArena(ctx->GetArena()) {
  ctx->PresentWalkConsTimer.Start();
  size_t pos = 0;
  for (const auto &iter : repo_tree) {
    WalkerVec.emplace_back(iter.first->NewPresentWalker(iter.second, from, to, false));
    Indy::TPresentWalker &walker = *WalkerVec.back();
    if (walker) {
      MinHeap.Insert(*walker, pos);
    }
    ++pos;
  }
  Valid = static_cast<bool>(MinHeap);
  Refresh();
  ctx->PresentWalkConsTimer.Stop();
}

TContext::TPresentWalker::~TPresentWalker() {}

void TContext::TPresentWalker::Refresh() {
  bool done = false;
  size_t pos;
  while (Valid) {
    const Indy::TPresentWalker::TItem &cur_item = MinHeap.Pop(pos);
    Indy::TPresentWalker &walker = *WalkerVec[pos];
    assert((*walker).KeyArena == cur_item.KeyArena);
    assert((*walker).OpArena == cur_item.OpArena);
    assert((*walker).SequenceNumber == cur_item.SequenceNumber);
    if (Item.KeyArena == nullptr || (Indy::TKey::TupleNeEq(Item.Key, Item.KeyArena, cur_item.Key, cur_item.KeyArena))) {
      Item = cur_item;
      if (!Item.Op.IsTombstone()) {
        done = true;
      }
    }
    ++walker;
    if (walker) {
      MinHeap.Insert(*walker, pos);
    }
    if (!done) {
      Valid = static_cast<bool>(MinHeap);
    } else {
      /* Phase 3 of #49: if the anchor entry was produced by a defer-safe
         commutative mutator, fold older same-mutator entries (and the
         eventual Assign base) into a single resolved value before
         returning. No-op when the anchor is an Assign. */
      if (Var::IsDeferSafeCommutative(Item.Mutator)) {
        ApplyDeferredFold();
      }
      break;
    }
  }
}

void TContext::TPresentWalker::ApplyDeferredFold() {
  /* Walk back through additional heap entries on the same key, folding
     them via Rt::Mutate. The loop terminates on:
       * Heap empty -- accumulated value stands (no Assign base existed;
         the commutative-mutator identity is "missing", matching the
         existing "first += against an empty key" semantics).
       * Different key -- next call to Refresh handles that key.
       * Tombstone on this key -- history below the tombstone is
         invisible; accumulated value stands.
       * Same key + Assign -- the base. Fold the accumulator onto it.
       * Same key + a different mutator -- mixed-mutator history, which
         TMutation::Augment already rejects at compose time. We surface
         the accumulator as-is and let downstream typed code react.

     Dedup: the SAME logical update can appear in two repos briefly
     during a Tetris push-to-parent / pop-from-child window. Both copies
     have the same UpdateId (the per-transaction TUuid from session.cc)
     but different per-repo SeqNums. We track seen UpdateIds and skip
     duplicates -- without this, the Wikipedia-pageviews demo's Go
     driver (which hammers tighter than the Python one) reproducibly
     double-counted ~1 per ~5,000 increments under contention. Entries
     with a zero UpdateId (e.g. the disk walker, which never hits the
     cross-repo Tetris window) are passed through without dedup. */
  const TMutator mut = Item.Mutator;
  void *state_alloc_a = alloca(Sabot::State::GetMaxStateSize() * 3);
  void *state_alloc_b = static_cast<uint8_t *>(state_alloc_a) + Sabot::State::GetMaxStateSize();
  void *state_alloc_c = static_cast<uint8_t *>(state_alloc_b) + Sabot::State::GetMaxStateSize();
  Var::TVar acc = Var::ToVar(*Sabot::State::TAny::TWrapper(Item.Op.NewState(Item.OpArena, state_alloc_a)));
  const Base::TUuid zero_uuid;
  std::vector<Base::TUuid> seen_update_ids;
  if (Item.UpdateId != zero_uuid) {
    seen_update_ids.push_back(Item.UpdateId);
  }

  while (MinHeap) {
    size_t peek_pos;
    const Indy::TPresentWalker::TItem &peek = MinHeap.Peek(peek_pos);
    if (Indy::TKey::TupleNeEq(Item.Key, Item.KeyArena, peek.Key, peek.KeyArena)) {
      break;
    }
    if (peek.Op.IsTombstone()) {
      break;
    }
    if (peek.Mutator != TMutator::Assign && peek.Mutator != mut) {
      break;
    }
    /* Commit to consuming this item. Copy the bits we need before Pop
       invalidates the underlying walker's Item slot. */
    const TMutator peek_mut = peek.Mutator;
    const Atom::TCore peek_op = peek.Op;
    Atom::TCore::TArena *const peek_op_arena = peek.OpArena;
    const Base::TUuid peek_update_id = peek.UpdateId;

    size_t consumed_pos;
    MinHeap.Pop(consumed_pos);

    /* Advance + reinsert the walker we just popped from regardless of
       whether we fold this entry. */
    Indy::TPresentWalker &consumed_walker = *WalkerVec[consumed_pos];
    ++consumed_walker;
    if (consumed_walker) {
      MinHeap.Insert(*consumed_walker, consumed_pos);
    }

    /* Dedup by UpdateId. If we've already consumed this logical
       update from another repo's walker in the same fold, drop it. */
    bool is_duplicate = false;
    if (peek_update_id != zero_uuid) {
      for (const auto &seen : seen_update_ids) {
        if (seen == peek_update_id) {
          is_duplicate = true;
          break;
        }
      }
    }
    if (is_duplicate) {
      continue;
    }
    if (peek_update_id != zero_uuid) {
      seen_update_ids.push_back(peek_update_id);
    }

    Var::TVar peek_val = Var::ToVar(*Sabot::State::TAny::TWrapper(peek_op.NewState(peek_op_arena, state_alloc_b)));
    if (peek_mut == TMutator::Assign) {
      /* Base. acc represents the accumulated RHS; result is base OP acc. */
      acc = Rt::Mutate(peek_val, mut, acc);
    } else {
      /* Same commutative mutator. */
      acc = Rt::Mutate(acc, mut, peek_val);
    }

    if (peek_mut == TMutator::Assign) {
      break;
    }
  }

  /* Stuff the resolved value back into Item.Op via FoldArena (owned by
     the enclosing TContext, so the TCore outlives this walker). Tag it
     as Assign so downstream consumers don't re-attempt the fold. */
  Item.Op = Atom::TCore(FoldArena, Sabot::State::TAny::TWrapper(Var::NewSabot(state_alloc_c, acc)).get());
  Item.OpArena = FoldArena;
  Item.Mutator = TMutator::Assign;
}

TContext::TKeyCursor::TKeyCursor(TContext *context, const Indy::TIndexKey &pattern)
    : Orly::TKeyCursor(context->Arena),
      Key(pattern),
      Valid(true),
      Cached(false),
      Csr(context, context->RepoTree, Key),
      ContextMembership(this) {
  ++(context->WalkerCount);
}

TContext::TKeyCursor::TKeyCursor(TContext *context, const Indy::TIndexKey &from, const Indy::TIndexKey &to)
    : Orly::TKeyCursor(context->Arena),
      Key(from),
      To(to),
      Valid(true),
      Cached(false),
      Csr(context, context->RepoTree, Key, To),
      ContextMembership(this) {
  ++(context->WalkerCount);
}

TContext::TKeyCursor::~TKeyCursor() {
  ContextMembership.Remove();
}

TContext::TKeyCursor::operator bool() const {
  Refresh();
  return Valid;
}

const Indy::TKey &TContext::TKeyCursor::operator*() const {
  Refresh();
  assert(Valid);
  assert(Cached);
  return Item;
}

const Indy::TKey *TContext::TKeyCursor::operator->() const {
  Refresh();
  assert(Valid);
  assert(Cached);
  return &Item;
}

TContext::TKeyCursor &TContext::TKeyCursor::operator++() {
  assert(Valid);
  Cached = false;
  ++Csr;
  ContextMembership.Remove();
  Refresh();
  return *this;
}

const TContext::TPresentWalker::TItem &TContext::TKeyCursor::GetVal() const {
  assert(Valid);
  assert(Csr);
  return *Csr;
}

void TContext::TKeyCursor::Refresh() const {
  if (Valid && !Cached) {
    Cached = true;
    if (Csr) {
      Item = Indy::TKey((*Csr).Key, (*Csr).KeyArena);
      /* insert ourselves into the thread local key cursor collection */
      ContextMembership.Insert(&(KeyCursorCollector->KeyCursorCollection));
    } else {
      Valid = false;
    }
  }
}