/* <orly/code_gen/variant.cc>

   Implements <orly/code_gen/variant.h>

   Copyright 2010-2026 Atomic Kismet Company

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

#include <orly/code_gen/variant.h>

#include <cstddef>

#include <base/as_str.h>
#include <base/path.h>
#include <orly/code_gen/obj.h>
#include <orly/type.h>
#include <orly/type/gen_code.h>
#include <orly/type/obj.h>
#include <orly/type/object_collector.h>
#include <orly/type/util.h>
#include <orly/type/variant.h>

using namespace std;
using namespace Orly;
using namespace Orly::CodeGen;
using namespace Orly::Type;

/* The generated native variant struct represents a value as:

     size_t  Which;          // index of the active arm, in asciibetical
                             // tag order (the order TVariantElems iterates)
     <PayloadT0> V<tag0>;     // payload storage, one field per arm
     <PayloadT1> V<tag1>;
     ...

   Only the field named by the active arm (Which) is meaningful; the
   others hold default-constructed junk. A tag-only arm (e.g. `Deleted`)
   has the empty-object payload type (`Orly::Rt::Objects::TObjO`, the unit
   value), so its field still default-constructs to the empty record --
   `Var::TVar(<empty-obj>)` yields `<{}>`, matching the
   single-key-record storage `<{.Deleted: <{}>}>` (issue #95).

   This mirrors the record generator (orly/code_gen/obj.cc): one payload
   field per arm rather than a C++ union, so that nested records/variants
   (which are not trivially destructible) need no manual lifetime
   management. Construction surface is Phase 3; here we emit one static
   factory per arm and a default + copy ctor.

   Ordering (EqEq/Neq/Match/MatchLess) compares Which first, then the
   active arm's payload. Because Which follows asciibetical tag order,
   this is consistent with the Var-level ordering in orly/var/impl.cc,
   which compares by tag-string then payload. */

void Orly::CodeGen::GenVariantHeader(const std::string &out_dir, const Type::TType &variant_type) {

  auto var_name = variant_type.GetMangledName();
  Base::TPath path(out_dir, var_name, vector<string>{"h"});
  auto class_name = "TVariant" + var_name;
  auto core_type = variant_type.As<Type::TVariant>();
  const auto &elems = core_type->GetElems();

  TCppPrinter out(AsStr(path));
  out << "/* <" << var_name << ".h>" << Eol
      << Eol
      << "   This file was auto-generated by the Orly compiler. */" << Eol
      << Eol
      << "#pragma once" << Eol
      << Eol
      << "#include <cassert>" << Eol
      << "#include <cstddef>" << Eol
      << Eol
      << "#include <orly/rt/tuple.h>" << Eol
      << "#include <orly/rt/containers.h>" << Eol
      << "#include <orly/rt/obj.h>" << Eol
      << "#include <orly/type/variant.h>" << Eol
      << "#include <orly/var/impl.h>" << Eol
      // AsVar() builds Var::TVar(<payload-field>) which, for record/variant
      // payloads, resolves to the templated TVar(const TCompound &) ctor whose
      // definition lives in <orly/var/obj.h>.
      << "#include <orly/var/obj.h>" << Eol
      // Native::State::Factory<Var::TVar> (write-side serialization, M2).
      << "#include <orly/var/new_sabot.h>" << Eol
      // Sabot::AsNative + the TToNativeVisitor we specialize for read-back (M2).
      << "#include <orly/sabot/to_native.h>" << Eol;

  /* Pull in any record/variant payload types we reference. */ {
    unordered_set<TType> obj_set;
    for (const auto &elem : elems) {
      CollectObjects(elem.second, obj_set);
    }
    if (obj_set.size()) {
      out << Eol
          << "/* Needed payload objects */" << Eol;
    }
    for (const auto &obj : obj_set) {
      // Record payloads are emitted by the record generator; variant payloads
      // (nested variants) by this generator. Route each include correctly.
      if (obj.Is<Type::TVariant>()) {
        GenVariantInclude(obj, out);
      } else {
        GenObjInclude(obj, out);
      }
    }
  }

  out << Eol;

  /* namespace Orly::Rt::Variants */ {
    TNamespacePrinter nsp(vector<string>{"Orly", "Rt"}, out);
    /* namespace Variants */ {
      TNamespacePrinter nsp(vector<string>{"Variants"}, out);
      out << "class " << class_name << " {" << Eol;
      /* Class body */ {
        TIndent indent(out);
        out << "public:" << Eol;

        /* Default ctor: arm 0, default payloads (set/dict mandate it). */
        out << class_name << "() : Which(0) {}" << Eol
            << Eol;

        /* Read-back from storage is handled by the Sabot::TToNativeVisitor
           specialization emitted below (a stored variant is a single-key
           record; the visitor reads the one key, dispatches on its tag, and
           builds this native variant via the per-arm static factories). */

        /* One static factory per arm. */
        {
          size_t idx = 0;
          for (const auto &elem : elems) {
            out << "static " << class_name << ' ' << elem.first
                << "(const " << elem.second << " &vv) {" << Eol
                << "  " << class_name << " out;" << Eol
                << "  out.Which = " << idx << ";" << Eol
                << "  out.V" << elem.first << " = vv;" << Eol
                << "  return out;" << Eol
                << "}" << Eol;
            ++idx;
          }
        }
        out << Eol;

        /* Copy ctor. */
        out << class_name << "(const " << class_name << " &that) : Which(that.Which)";
        for (const auto &elem : elems) {
          out << ", V" << elem.first << "(that.V" << elem.first << ')';
        }
        out << " {}" << Eol
            << Eol;

        /* AsVar(): build a Var::TVariant for the active arm. Declared here,
           defined out-of-line below (it needs the full declared type from the
           TDt specialization, which the value must carry so a set of
           differently-tagged variants is homogeneous -- see #95). */
        out << "Var::TVar AsVar() const;" << Eol
            << Eol;

        /* GetHash(): hash the active arm's tag-index and payload. */
        out << "size_t GetHash() const {" << Eol
            << "  assert(this);" << Eol
            << "  switch (Which) {" << Eol;
        {
          size_t idx = 0;
          for (const auto &elem : elems) {
            out << "    case " << idx << ": return std::hash<size_t>()(" << idx
                << ") ^ std::hash<" << elem.second << ">()(V" << elem.first << ");" << Eol;
            ++idx;
          }
        }
        out << "  }" << Eol
            << "  assert(false);" << Eol
            << "  return 0;" << Eol
            << "}" << Eol
            << Eol;

        /* EqEq(): same arm and equal payload. */
        out << "bool EqEq(const " << class_name << " &that) const {" << Eol
            << "  assert(this);" << Eol
            << "  assert(&that);" << Eol
            << "  if (Which != that.Which) { return false; }" << Eol
            << "  switch (Which) {" << Eol;
        {
          size_t idx = 0;
          for (const auto &elem : elems) {
            out << "    case " << idx << ": return Rt::EqEq(V" << elem.first
                << ", that.V" << elem.first << ");" << Eol;
            ++idx;
          }
        }
        out << "  }" << Eol
            << "  assert(false);" << Eol
            << "  return false;" << Eol
            << "}" << Eol
            << Eol;

        /* Neq(): negation of EqEq. */
        out << "bool Neq(const " << class_name << " &that) const {" << Eol
            << "  assert(this);" << Eol
            << "  assert(&that);" << Eol
            << "  return !EqEq(that);" << Eol
            << "}" << Eol
            << Eol;

        /* Match(): structural equality; same shape as EqEq for variants. */
        out << "bool Match(const " << class_name << " &that) const {" << Eol
            << "  assert(this);" << Eol
            << "  assert(&that);" << Eol
            << "  if (Which != that.Which) { return false; }" << Eol
            << "  switch (Which) {" << Eol;
        {
          size_t idx = 0;
          for (const auto &elem : elems) {
            out << "    case " << idx << ": return Rt::Match(V" << elem.first
                << ", that.V" << elem.first << ");" << Eol;
            ++idx;
          }
        }
        out << "  }" << Eol
            << "  assert(false);" << Eol
            << "  return false;" << Eol
            << "}" << Eol
            << Eol;

        /* MatchLess(): order by active arm index, then the active payload.
           Consistent with the Var-level tag-then-payload ordering. */
        out << "bool MatchLess(const " << class_name << " &that) const {" << Eol
            << "  assert(this);" << Eol
            << "  assert(&that);" << Eol
            << "  if (Which != that.Which) { return Which < that.Which; }" << Eol
            << "  switch (Which) {" << Eol;
        {
          size_t idx = 0;
          for (const auto &elem : elems) {
            out << "    case " << idx << ": return Rt::MatchLess(V" << elem.first
                << ", that.V" << elem.first << ");" << Eol;
            ++idx;
          }
        }
        out << "  }" << Eol
            << "  assert(false);" << Eol
            << "  return false;" << Eol
            << "}" << Eol
            << Eol;

        /* Accessors. The per-arm payload getter asserts the arm is active. */
        out << "size_t GetWhich() const {" << Eol
            << "  assert(this);" << Eol
            << "  return Which;" << Eol
            << "}" << Eol;
        {
          size_t idx = 0;
          for (const auto &elem : elems) {
            out << elem.second << " GetV" << elem.first << "() const {" << Eol
                << "  assert(this);" << Eol
                << "  assert(Which == " << idx << ");" << Eol
                << "  return V" << elem.first << ";" << Eol
                << "}" << Eol;
            ++idx;
          }
        }

        out << Eol
            << "private:" << Eol
            << "size_t Which;" << Eol;
        for (const auto &elem : elems) {
          out << elem.second << " V" << elem.first << ";" << Eol;
        }

      } // Class body
      out << "}; // " << class_name << Eol;
    } // namespace Variants

    /* EqEq / Neq / Match / MatchLess dispatch structs, mirroring records. */
    out << Eol
        << "template <>" << Eol
        << "struct EqEqStruct<Variants::" << class_name << ", Variants::" << class_name << "> {" << Eol
        << "  static bool Do(const Variants::" << class_name << " &lhs, const Variants::"
        << class_name << " &rhs) {" << Eol
        << "    return lhs.EqEq(rhs);" << Eol
        << "  }" << Eol
        << "}; // EqEqStruct" << Eol
        << Eol
        << "template <>" << Eol
        << "struct NeqStruct<Variants::" << class_name << ", Variants::" << class_name << "> {" << Eol
        << "  static bool Do(const Variants::" << class_name << " &lhs, const Variants::"
        << class_name << " &rhs) {" << Eol
        << "    return lhs.Neq(rhs);" << Eol
        << "  }" << Eol
        << "}; // NeqStruct" << Eol
        << Eol
        << "template <>" << Eol
        << "inline bool Match(const Variants::" << class_name << " &lhs, const Variants::"
        << class_name << " &rhs) {" << Eol
        << "  return lhs.Match(rhs);" << Eol
        << "}" << Eol
        << "template <>" << Eol
        << "inline bool MatchLess(const Variants::" << class_name << " &lhs, const Variants::"
        << class_name << " &rhs) {" << Eol
        << "  return lhs.MatchLess(rhs);" << Eol
        << "}" << Eol;
  } // namespace Orly::Rt

  out << Eol;

  /* namespace Orly::Type: TDt<...>::GetType() -> TVariant::Get(...). */ {
    TNamespacePrinter nsp(vector<string>{"Orly", "Type"}, out);
    out << "template <>" << Eol
        << "struct TDt<Rt::Variants::" << class_name << "> {" << Eol
        << Eol
        << "  static TType GetType() {" << Eol
        << "    return TVariant::Get({"
        << Base::Join(elems,
                      ", ",
                      [](TCppPrinter &out, const TVariant::TElems::value_type &it) {
                        out << "{\"" << it.first << "\", ";
                        Type::GenCode(out.GetOstream(), it.second);
                        out << '}';
                      })
        << "});" << Eol
        << "  }" << Eol
        << Eol
        << "};" << Eol;
  } // namespace Orly::Type

  out << Eol;

  /* Out-of-line AsVar(): build a Var::TVariant for the active arm, carrying
     the FULL declared variant type (from TDt above) so a set of differently-
     tagged variants is homogeneous at the Var layer (#95). Routes through the
     single-key-record encoding via TVar::Variant; the payload becomes
     Var::TVar(<active field>). No empty-object trap (#90): a tag-only arm
     still carries its empty-record payload. */ {
    TNamespacePrinter nsp(vector<string>{"Orly", "Rt", "Variants"}, out);
    out << "inline Var::TVar " << class_name << "::AsVar() const {" << Eol
        << "  assert(this);" << Eol
        << "  switch (Which) {" << Eol;
    {
      size_t idx = 0;
      for (const auto &elem : elems) {
        out << "    case " << idx << ": return Var::TVar::Variant("
            << "Type::TDt<Rt::Variants::" << class_name << ">::GetType(), \""
            << elem.first << "\", Var::TVar(V" << elem.first << "));" << Eol;
        ++idx;
      }
    }
    out << "  }" << Eol
        << "  assert(false);" << Eol
        << "  throw Rt::TSystemError(HERE, \"variant has no active arm\");" << Eol
        << "}" << Eol;
  } // namespace Orly::Rt::Variants

  out << Eol;

  /* Read-back (#95 Phase 3 M2): a stored variant is a single-key record
     (`Integer(7)` -> `<{.Integer: 7}>`). The generic TToNativeVisitor walks
     fixed record fields, which a variant doesn't have, so specialize it: read
     the single key, dispatch on its tag, and build this native variant via the
     per-arm static factories (payload deserialized with AsNative). */ {
    TNamespacePrinter nsp(vector<string>{"Orly", "Sabot"}, out);
    out << "template <>" << Eol
        << "class TToNativeVisitor<Rt::Variants::" << class_name << "> final : public TStateVisitor {" << Eol
        << "  NO_COPY(TToNativeVisitor);" << Eol
        << "  public:" << Eol
        << "  TToNativeVisitor(Rt::Variants::" << class_name << " &out) : Out(out) {}" << Eol;
    {
      static const char *const kNonRecord[] = {
          "TFree", "TTombstone", "TVoid", "TInt8", "TInt16", "TInt32", "TInt64",
          "TUInt8", "TUInt16", "TUInt32", "TUInt64", "TBool", "TChar", "TFloat",
          "TDouble", "TDuration", "TTimePoint", "TUuid", "TBlob", "TStr", "TDesc",
          "TOpt", "TSet", "TVector", "TMap", "TTuple"};
      for (const char *const s : kNonRecord) {
        out << "  virtual void operator()(const State::" << s
            << " &) const override { THROW_ERROR(TInvalidConversion); }" << Eol;
      }
    }
    out << "  virtual void operator()(const State::TRecord &state) const override {" << Eol
        << "    void *type_alloc = alloca(Type::GetMaxTypeSize());" << Eol
        << "    Type::TRecord::TWrapper rtype(state.GetRecordType(type_alloc));" << Eol
        << "    void *type_pin_alloc = alloca(Type::GetMaxTypePinSize());" << Eol
        << "    Type::TRecord::TPin::TWrapper tpin(rtype->Pin(type_pin_alloc));" << Eol
        << "    void *state_pin_alloc = alloca(State::GetMaxStatePinSize());" << Eol
        << "    State::TRecord::TPin::TWrapper spin(state.Pin(state_pin_alloc));" << Eol
        << "    if (tpin->GetElemCount() != 1) { THROW_ERROR(TInvalidConversion); }" << Eol
        << "    std::string tag;" << Eol
        << "    void *etype_alloc = alloca(Type::GetMaxTypeSize());" << Eol
        << "    Type::TAny::TWrapper(tpin->NewElem(0, tag, etype_alloc));" << Eol
        << "    void *estate_alloc = alloca(State::GetMaxStateSize());" << Eol
        << "    State::TAny::TWrapper elem_state(spin->NewElem(0, estate_alloc));" << Eol;
    {
      size_t idx = 0;
      for (const auto &elem : elems) {
        out << "    " << (idx == 0 ? "if" : "else if") << " (tag == \"" << elem.first
            << "\") { Out = Rt::Variants::" << class_name << "::" << elem.first
            << "(AsNative<" << elem.second << ">(*elem_state)); }" << Eol;
        ++idx;
      }
    }
    out << "    else { THROW_ERROR(TInvalidConversion); }" << Eol
        << "  }" << Eol
        << "  private:" << Eol
        << "  Rt::Variants::" << class_name << " &Out;" << Eol
        << "}; // TToNativeVisitor" << Eol;
  } // namespace Orly::Sabot

  out << Eol;

  /* namespace Orly::Native: write-side serialization (#95 Phase 3 M2).
     The generic State::Factory<TVal> assumes a fixed-shape record; a variant
     value instead serializes as the *active arm's* single-key record. Route
     through AsVar() -> Var::TVariant -> Var::NewSabot, which reuses the
     Phase-1 SS::TObj(const Var::TVariant *) adapter (the single-key-record
     encoding). The State::Factory<Var::TVar> specialization that does this
     lives in <orly/var/new_sabot.h> (included above). */ {
    TNamespacePrinter nsp(vector<string>{"Orly", "Native"}, out);
    out << "template <>" << Eol
        << "class State::Factory<Rt::Variants::" << class_name << "> final {" << Eol
        << "  NO_CONSTRUCTION(Factory);" << Eol
        << "  public:" << Eol
        << "  static Sabot::State::TAny *New(const Rt::Variants::" << class_name
        << " &val, void *state_alloc) {" << Eol
        << "    return State::Factory<Var::TVar>::New(val.AsVar(), state_alloc);" << Eol
        << "  }" << Eol
        << "}; // State::Factory<" << class_name << ">" << Eol;
  } // namespace Orly::Native

  out << Eol;

  /* std::hash specialization. */
  out << "namespace std {" << Eol;
  {
    TIndent indent(out);
    out << "template<>" << Eol
        << "struct hash<Orly::Rt::Variants::" << class_name << "> {" << Eol << Eol
        << "  typedef size_t return_type;" << Eol
        << "  typedef Orly::Rt::Variants::" << class_name << " argument_type;" << Eol << Eol
        << "  size_t operator()(const argument_type &v) const {" << Eol
        << "    return v.GetHash();" << Eol
        << "  }" << Eol << Eol
        << "}; // hash" << Eol;
  }
  out << "} // std" << Eol;
}

void Orly::CodeGen::GenVariantInclude(const Type::TType &variant_type, TCppPrinter &out) {
  /* Variant headers are emitted into the same out_dir as record headers
     (orly/rt/objects/) -- their 'V'-prefixed mangled names never collide
     with the 'O'-prefixed record names. */
  out << "#include <orly/rt/objects/" << variant_type.GetMangledName() << ".h>" << Eol;
}
