/* <orly/compiler.cc>

   Implements <orly/compiler.h>

   Copyright 2010-2026 Atomic Kismet Company

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

#include <orly/compiler.h>

#include <algorithm>
#include <cassert>
#include <cstring>
#include <fstream>
#include <memory>
#include <mutex>
#include <optional>
#include <queue>
#include <unistd.h>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include <base/as_str.h>
#include <base/murmur.h>
#include <base/split.h>
#include <base/source_root.h>
#include <base/subprocess.h>
#include <orly/code_gen/cpp_printer.h>
#include <orly/code_gen/package.h>
#include <orly/orly.package.cst.h>
#include <orly/symbol/import_function.h>
#include <orly/synth/context.h>
#include <orly/synth/package.h>

/* The compiler build stamp, part of every staleness key (#312): generated
   C++ depends on the compiler that emitted it, not just on the source.
   Generated by `make version`; absent under a direct jhm invocation, in
   which case the stamp is "unknown" and the staleness cache is disabled
   entirely (an unstamped dev build must never serve stale codegen). */
#if __has_include(<orly/build_version.h>)
#include <orly/build_version.h>
#endif
#ifndef ORLY_BUILD_VERSION
#define ORLY_BUILD_VERSION "unknown"
#endif

using namespace Base;
using namespace std;
using namespace Orly;
using namespace Orly::Compiler;
using namespace Jhm;

/* Compiles a orlyscript package. On construction it builds to the symbolic layer. It can be asked to emit the
   necessary C++ */
class TPackageBuilder {
  NO_COPY(TPackageBuilder);
  public:

  TPackageBuilder(const TRelPath &rel_path) : RelPath(rel_path) {}
  TPackageBuilder(TPackageBuilder &&that)
      : RelPath(move(that.RelPath)), Cst(move(that.Cst)), Synth(move(that.Synth)) {}

  void BuildSymbols(const TTree &src_root) {
    Cst = Package::Syntax::TPackage::ParseFile(AsStr(src_root.GetAbsPath(RelPath)).c_str());
    if (!Cst.HasErrors() && !Synth::GetContext().HasErrors()) {
      assert(Cst.Get());
      Synth = make_unique<Synth::TPackage>(Package::TName{RelPath.Path.ToNamespaceIncludingName()}, &*Cst.Get(), false);
    }
  }

  bool HasErrors() {
    return Cst.HasErrors() || Synth::GetContext().HasErrors();
  }

  void PrintErrors(ostream &out) const {
    Cst.PrintErrors(out);
    Synth::GetContext().PrintErrors(out);
  }

  /* Generates the '.h' interfaces, as well as the '.cc' implementations.
     `emitted_objs` is the compile walk's shared already-emitted set (#312):
     object headers a previous package of this walk emitted are skipped. */
  void GenerateIntermediateCode(const TTree &out_root, std::unordered_set<Type::TType> &emitted_objs) {
    //Generate the CodeGen representation
    CodeGen::TPackage cg(Synth->GetSymbol());
    //Spit out the cc file for the package
    cg.Emit(out_root);

    //Spit out the language object files as necessary (Everything in the header to simplify linking.)
    cg.EmitObjectHeaders(GetSrcRoot() + "orly/rt/objects", emitted_objs);
  }

  Package::TName GetName() const {
    assert(Synth);
    return Synth->GetName();
  }

  unsigned int GetVersion() const {
    assert(Synth);

    return Synth->GetVersion();
  }

  void TypeCheck() const {
    assert(Synth);
    Synth->GetSymbol()->TypeCheck();
  }

  /* The source-relative paths of the packages this one imports (#171). Each
     import lowered to a Symbol::TImportFunction carrying its source package name
     (e.g. `imports/lib`); convert that to the package's `.orly` rel path so the
     compile driver can build it as a dependency. Call after BuildSymbols. */
  std::vector<TRelPath> GetImportPackages() const {
    assert(Synth);
    std::vector<TRelPath> ret;
    for (const auto &func : Synth->GetSymbol()->GetFunctions()) {
      auto import_func = dynamic_cast<const Symbol::TImportFunction *>(func.get());
      if (!import_func) {
        continue;
      }
      const auto &parts = import_func->GetPackageName().Name;
      assert(!parts.empty());
      Base::TPath path(
          Base::TPath::TStrList(parts.begin(), parts.end() - 1),  // namespace
          parts.back(),                                           // name
          Base::TPath::TStrList{"orly"});                         // extension
      ret.emplace_back(move(path));
    }
    return ret;
  }

  private:
  TRelPath RelPath;

  Tools::Nycr::TContextBuilt<Package::Syntax::TPackage> Cst;
  //note: symbolic is owned by synth, and we don't have a good reason to pull it out at the moment.
  unique_ptr<Synth::TPackage> Synth;

};  // TPackageBuilder


/* Whole-file read for staleness checks (#312); nullopt if unreadable. */
static optional<string> TryReadFile(const string &path) {
  ifstream in(path, ios::binary);
  if (!in) {
    return nullopt;
  }
  return string(istreambuf_iterator<char>(in), istreambuf_iterator<char>{});
}

/* 64-bit Murmur over a byte string. The trailing length word keeps the
   zero-padding of the last word from aliasing real trailing NUL bytes. */
static uint64_t HashBytes(const string &bytes) {
  vector<uint64_t> words((bytes.size() + 7) / 8 + 1, 0);
  memcpy(words.data(), bytes.data(), bytes.size());
  words.back() = bytes.size();
  return Murmur(words.data(), words.size(), 0);
}

//Note: This should probably be promted to a compile management class.
/* Returns the versioned package name of the final build target. */
Package::TVersionedName Orly::Compiler::Compile(
      TPath core_file,
      const TTree &out_tree,
      const TOptions &options,
      ostream &out_strm) {
  const bool machine_mode = options.MachineMode;
  /* Nabbed by Compile() to prevent multiple threads from trying to compile. */
  static mutex Compiling;

  lock_guard<mutex> lock_compiling(Compiling);
  Synth::GetContext().ClearErrors();

  /* Find the package-tree root: the nearest ancestor directory holding an
     `__orly__` marker. Inside a tree, every package (the core file and any it
     imports) is named relative to that root, so cross-package refs like
     `package <imports/lib>#1` resolve against one shared src tree. Outside a
     tree (no `__orly__`), keep the legacy behavior -- the file's own directory
     is the root and its package name is just the file name -- and imports are
     rejected (see the dependency loop below). */
  std::string core_dir;
  for (const auto &part : core_file.Namespace) {
    core_dir += '/';
    core_dir += part;
  }
  bool found_root = false;
  TTree root_tree = TTree::Find(core_dir, "__orly__", found_root);

  /* Copy the namespace for the no-root fallback tree: we still need core_file's
     namespace below to compute core_rel, so it must not be moved out here. */
  TTree src_tree = found_root ? root_tree : TTree(std::vector<std::string>(core_file.Namespace));
  /* core_rel = the core file relative to src_tree: strip the root's namespace
     components (none when there is no root, leaving just the file name). */
  size_t strip = found_root ? root_tree.Root.size() : core_file.Namespace.size();
  core_file.Namespace.erase(core_file.Namespace.begin(), core_file.Namespace.begin() + strip);
  const TRelPath core_rel(move(core_file));
  //NOTE: As of here, core_file has nothing left in it.

  typedef unordered_map<TRelPath, unique_ptr<TPackageBuilder>> TPackageMap;
  TPackageMap packages;
  packages.insert(make_pair(core_rel, make_unique<TPackageBuilder>(core_rel)));

  bool failed = false;

  /* The staleness cache (#312) only runs when its key is trustworthy: a
     debug compile wants fresh -g output, a transient compile leaves nothing
     to reuse, and an unstamped compiler build can't tell its own codegen
     apart from an older build's. */
  const bool cache_enabled =
      !options.DebugCc && !options.TransientCc && string(ORLY_BUILD_VERSION) != "unknown";
  /* Every package's staleness key, in walk order. An empty key means the
     source couldn't be hashed; that package (and the link step, which
     depends on every key) then compiles uncached. */
  vector<pair<TRelPath, string>> package_keys;
  /* Object types whose shared headers this walk has already emitted. */
  unordered_set<Type::TType> emitted_objs;
  /* out_tree path of a package's generated file with the given extension. */
  const auto out_path_for = [&out_tree](const TRelPath &rel, const vector<string> &ext) {
    return AsStr(out_tree.GetAbsPath(SwapExtension(TPath(rel.Path), ext)));
  };
  /* The four files GenerateIntermediateCode emits into out_tree per package. */
  static const vector<vector<string>> GeneratedExts{{"h"}, {"cc"}, {"link", "cc"}, {"orly", "sig"}};

  /* extra */ {
    queue<TRelPath> todo;
    todo.push(core_rel);

    do {
      auto cur = todo.front();
      todo.pop();

      if (cur.Path.Extension.size() != 1 || cur.Path.Extension[0] != "orly") {
        out_strm << "Invalid package name. Package names may not contain a '.'. This means, for example, a source file can only be 'a.orly', not 'a.foo.orly'" << endl;
        failed = true;
        break;
      }

      auto &builder = packages[cur];
      /* Report the current package's errors and flag the build as failed
         (the caller then breaks out of the build loop). */
      auto note_errors = [&] {
        out_strm << "Errors in: " << cur << endl;
        builder->PrintErrors(out_strm);
        failed = true;
      };
      if (machine_mode) {
        out_strm << "MM_NOTICE: Synth + Symbols" << endl;
      }
      builder->BuildSymbols(src_tree);
      if (builder->HasErrors()) {
        note_errors();
        break;
      }
      if (!options.SyntaxOnly) {
        if (machine_mode) {
          out_strm << "MM_NOTICE: TypeCheck" << endl;
        }
        builder->TypeCheck();
        if (builder->HasErrors()) {
          note_errors();
          break;
        }
      }
      /* Imports (#171): enqueue each imported package as a dependency to build.
         The end-of-compile link step then links every package in the map. */
      for (const auto &dep : builder->GetImportPackages()) {
        if (packages.count(dep)) {
          continue;  // already queued / built (dedup; the dependency graph may share packages)
        }
        if (!found_root) {
          out_strm << "Cross-package imports require an Orly package tree (an __orly__ file at its root)." << endl;
          failed = true;
          break;
        }
        packages.insert(make_pair(dep, make_unique<TPackageBuilder>(dep)));
        todo.push(dep);
      }
      if (failed) {
        break;
      }
      if (options.SyntaxOnly || options.SemanticOnly) {
        continue;  // check-only modes still walk imports but never emit
      }
      if (machine_mode) {
        out_strm << "MM_NOTICE: Code Gen" << endl;
      }
      /* Staleness key (#312): a content hash of the source plus the compiler
         build stamp. mtime-vs-source would be wrong here -- codegen output
         changes when the compiler does, not just when the source does. */
      string pkg_key;
      if (const auto src = TryReadFile(AsStr(src_tree.GetAbsPath(cur)))) {
        pkg_key = AsStr(hex, HashBytes(*src), ' ', ORLY_BUILD_VERSION);
      }
      const string key_path = out_path_for(cur, {"orlyc", "key"});
      package_keys.emplace_back(cur, pkg_key);
      if (cache_enabled && !pkg_key.empty() && TryReadFile(key_path) == pkg_key) {
        /* The key was written by a compile of this exact source with this
           exact compiler, so if its outputs are still present they are
           byte-identical to what this compile would emit -- including the
           shared object headers that compile put under orly/rt/objects
           (deleting those by hand without touching out_tree is the one way
           to fool this check). */
        if (ranges::all_of(GeneratedExts, [&](const vector<string> &ext) {
              return access(out_path_for(cur, ext).c_str(), R_OK) == 0;
            })) {
          continue;
        }
      }
      builder->GenerateIntermediateCode(out_tree, emitted_objs);
      if (packages[cur]->HasErrors()) {
        note_errors();
        break;
      }
      if (cache_enabled && !pkg_key.empty()) {
        CodeGen::TCppPrinter key_out(key_path, "staleness key");
        key_out << pkg_key;
      }
    } while (!todo.empty());
  }

  if(failed) {
    throw TCompileFailure(HERE, "Compiling Orly language");
  }

  auto versioned_name = Package::TVersionedName{
      packages[core_rel]->GetName(), packages[core_rel]->GetVersion()};

  if (options.SyntaxOnly || options.SemanticOnly) {
    return versioned_name;
  }

  /* extra */ {
    if(machine_mode) {
      out_strm << "MM_NOTICE: Compiling C++" << endl;
    }

    const string so_path = out_path_for(core_rel, {to_string(packages[core_rel]->GetVersion()), "so"});

    /* Link staleness (#312): the .so is a pure function of every package's
       key. Sorted for determinism -- package_keys is in walk order, which
       varies with the import graph's hash order. Empty only when caching is
       off or some package's source couldn't be hashed. */
    const string link_key_path = out_path_for(core_rel, {"link", "key"});
    string link_key;
    if (cache_enabled &&
        ranges::none_of(package_keys, [](const auto &rel_key) { return rel_key.second.empty(); })) {
      auto sorted_keys = package_keys;
      ranges::sort(sorted_keys, {}, [](const auto &rel_key) { return AsStr(rel_key.first); });
      for (const auto &[rel, key] : sorted_keys) {
        link_key += AsStr(rel, ' ', key, '\n');
      }
    }
    if (!link_key.empty() && TryReadFile(link_key_path) == link_key &&
        access(so_path.c_str(), R_OK) == 0) {
      return versioned_name;  // the linked .so is already exactly this compile's output
    }

    vector<string> gcc_cmd{"g++", "-std=c++23", "-xc++", "-I" + GetSrcRoot(), "-fPIC", "-shared", "-o",
                           so_path,
                           "-iquote", AsStr(out_tree),
                           out_path_for(core_rel, {"link", "cc"})};
    // Take all the packages needed directly or indirectly by the compilation and link them together in one swoop.
    for (const auto &package : packages) {
      gcc_cmd.emplace_back(out_path_for(package.first, {"cc"}));
    }

    /* Warning configuration applied to both debug and release.
       Deliberately NO -Werror -- warnings come overwhelmingly from the
       orly headers themselves (e.g. -Waddress-of-packed-member on
       TCore's union, -Wclass-memaccess on packed serialization layouts)
       rather than from anything the user's .orly file caused us to
       emit. Errror'ing on them just breaks `orlyc` for users whenever
       a new gcc release adds a warning category, with no recourse
       except waiting for a fix in this repo. Print warnings, but don't
       fail the compile.
       The -Wno-* list mirrors root.jhm so generated-code compilation
       sees the same noise filter as the in-tree build. */
    const char *common_warning_args[] = {
        "-Wall", "-Wextra",
        "-Wno-unused-variable", "-Wno-unused-parameter", "-Wno-unused-result",
        "-Wno-parentheses", "-Wno-type-limits",
        "-Wno-address-of-packed-member", "-Wno-deprecated-declarations",
        "-Wno-class-memaccess", "-Wno-stringop-overflow", "-Wno-stringop-overread",
        "-Wno-array-bounds", "-Wno-restrict", "-Wno-pessimizing-move",
        "-Wno-redundant-move", "-Wno-mismatched-new-delete",
        "-Wno-dangling-reference", "-Wno-tautological-compare",
        "-Wno-implicit-fallthrough", "-Wno-overloaded-virtual",
        "-Wno-deprecated", "-Wno-deprecated-copy", "-Wno-c++20-compat",
        "-Wno-volatile", "-Wno-narrowing", "-Wno-maybe-uninitialized",
        "-Wno-init-list-lifetime", "-Wno-deprecated-enum-enum-conversion",
        "-Wno-deprecated-enum-float-conversion", "-Wno-int-in-bool-context",
        "-Wno-uninitialized", "-Wno-sign-compare", "-Wno-empty-body",
        "-Wno-misleading-indentation", "-Wno-terminate", "-Wno-noexcept-type",
        "-Wno-comment", "-Wno-reorder", "-Wno-strict-overflow",
        "-Wno-shift-negative-value", "-Wno-zero-as-null-pointer-constant",
        "-Wno-write-strings", "-Wno-multichar", "-Wno-int-to-pointer-cast",
        "-Wno-pointer-arith", "-Wno-format", "-Wno-format-security",
        "-Wno-ignored-qualifiers", "-Wno-cast-function-type",
        "-Wno-aligned-new", "-Wno-placement-new",
        "-Wno-format-truncation", "-Wno-format-overflow",
        "-Wno-nonnull-compare", "-Wno-nonnull",
    };
    for (auto &arg : common_warning_args) {
      gcc_cmd.emplace_back(arg);
    }
    if (options.DebugCc) {
      gcc_cmd.push_back("-g");
    } else {
      gcc_cmd.push_back("-O2");
      gcc_cmd.push_back("-DNDEBUG");
    }

    TPump pump;
    auto subproc = TSubprocess::New(pump, gcc_cmd);
    auto status = subproc->Wait();
    if (status || failed) {
      /* Always surface the compiler's own diagnostics (#533): without them
         an environment-shaped failure -- a missing system header, a bad
         ORLY_SRC_ROOT, toolchain drift -- is undiagnosable. This used to be
         gated behind -d, dead-ending users at a generic message. */
      EchoOutput(subproc->TakeStdOutFromChild());
      EchoOutput(subproc->TakeStdErrFromChild());
      out_strm << "Error while compiling the generated C++ (g++ diagnostics above; the generated sources are kept in the output directory)" << endl;
      throw TCompileFailure(HERE, "Compiling C++ and linking");
    }

    if (!link_key.empty()) {
      CodeGen::TCppPrinter key_out(link_key_path, "link staleness key");
      key_out << link_key;
    }

    /* TransientCc (#312): the .so is the product; drop the generated C++
       intermediates (and any stale keys from earlier cached compiles, which
       would otherwise vouch for files this just removed). Object headers
       stay -- they live under the shared orly/rt/objects tree. */
    if (options.TransientCc) {
      for (const auto &package : packages) {
        for (const auto &ext : GeneratedExts) {
          unlink(out_path_for(package.first, ext).c_str());
        }
        unlink(out_path_for(package.first, {"orlyc", "key"}).c_str());
      }
      unlink(link_key_path.c_str());
    }
  }

  return versioned_name;
}
