/* <orly/orly.cc>

   The controller for the orly compiler. Runs all the phases, exits on first phase failure.

   Copyright 2010-2026 Atomic Kismet Company

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

#include <chrono>
#include <memory>
#include <ostream>

#include <unistd.h>

#include <base/cmd.h>
#include <base/scheduler.h>
#include <orly/compiler.h>
#include <orly/error.h>
#include <orly/server/server.h>
#include <orly/server/session.h>
#include <orly/type.h>
#include <orly/type/type_czar.h>
#include <base/util/path.h>

/* Generated by `make version` (see Makefile); absent under a direct jhm
   invocation, in which case the build reports "unknown". */
#if __has_include(<orly/build_version.h>)
#include <orly/build_version.h>
#endif
#ifndef ORLY_BUILD_VERSION
#define ORLY_BUILD_VERSION "unknown"
#endif

using namespace std;
using namespace Orly;

class TCompilerConfig : public Base::TCmd {
  public:
  TCompilerConfig(int argc, char **argv)
      : DebugOutput(false),
        InfoReport(false),
        MachineForm(false),
        OutputDir(Util::GetCwd()),
        SemanticOnly(false),
        SkipTests(false),
        VerboseTests(false) {

    Parse(argc, argv, TMeta());
  }

  private:

  class TMeta : public TCmd::TMeta {
    public:
    TMeta() : TCmd::TMeta("Orly Compiler v0.5") {
      Param(&TCompilerConfig::DebugOutput, "debug_output", Optional, "debug\0d\0", "Compile the orly package in debug mode.");
      Param(&TCompilerConfig::MachineForm, "machine_form", Optional, "machine-form\0m\0", "Print out machine readable progress.");
      Param(&TCompilerConfig::OutputDir, "output_directory", Optional, "output\0o\0", "The directory to write output to.");
      Param(&TCompilerConfig::SemanticOnly, "semantic_only", Optional, "semantic-only\0", "Don't actually produce output, just syntactically and semantically validate the program.");
      Param(&TCompilerConfig::SkipTests, "skip_tests", Optional, "skip-tests\0", "Don't run tests after compiling.");
      Param(&TCompilerConfig::VerboseTests, "verbose_tests", Optional, "v\0",
          "Run tests in 'verbose' mode, printing out the result of every test, rather than just failing tests.");
      Param(&TCompilerConfig::Source, "source", Required, "The Orly source file to compile.");
    }

    private:
    virtual void WriteAfterDesc(std::ostream &strm) const {
      strm << "Build: " << ORLY_BUILD_VERSION << endl
           << endl
           << "Copyright Atomic Kismet Company" << endl
           << "Licensed under the Apache License, Version 2.0" << endl;
    }

  };  // TMeta

  virtual TCmd::TMeta *NewMeta() const {
    return new TMeta();
  }

  public:
  //NOTE: These should really be private w/ accessors but I'm going for quick right now, not pretty.
  bool DebugOutput;
  bool InfoReport;
  bool MachineForm;
  std::string OutputDir;
  bool SemanticOnly;
  std::string Source;
  bool SkipTests;
  bool VerboseTests;
};

/* Run the freshly-compiled package's test{} blocks on an in-process indy
   server (#262), instead of the legacy SPA flux_capacitor engine. Stands up a
   short-lived, memory-simulated TServer (no disk, ephemeral/no listener ports,
   tiny fixed pools so 158 lang_test invocations don't blow up RAM), installs
   the package, and runs RunTestSuite. Returns true iff every test passed. */
/* TServer::TCmd's default ctor is protected (it's meant to be subclassed by a
   binary's arg parser, as orlyi does); subclass it so we can default-construct
   and tweak fields directly. */
class TIndyTestServerCmd final : public Orly::Server::TServer::TCmd {
  public:
  TIndyTestServerCmd() : Orly::Server::TServer::TCmd() {}
};

static bool RunTestsOnIndy(const Package::TVersionedName &output, const TCompilerConfig &cmd) {
  int result_code = EXIT_FAILURE;
  /* The server's fiber machinery (transactions, the engine) must run inside a
     scheduler/fiber context -- the same context RunUntilCtrlC gives its main
     job (orlyi constructs its TServer there too). We do the work in that job.

     Teardown is now a first-class operation (#440): Shutdown() flushes and
     stops everything in order, the destructor is safe afterward, and the job
     returning quiesces the scheduler (which synthesizes the ctrl-c that
     RunUntilCtrlC waits for).  Every orlyc test run therefore doubles as a
     construct/run/destroy smoke of the whole server.  The two thread-local
     pool MANAGERS are intentionally released, not destroyed: pools created
     on scheduler-worker threads cannot be reclaimed without thread-exit
     hooks, and the managers' destructors (correctly) refuse to die while
     pools exist. */
  /* The worker cap must cover every long-lived job the server schedules
     (runner hosts for replication/mergers/cleaners, discard runners, tetris,
     accept loops, ...): TScheduler::Schedule queues past the cap but never
     launches another worker, so an 8-worker scheduler silently never ran the
     last ~6 jobs -- and a loop that never runs can neither do its part of
     the update pipeline nor confirm its exit to Shutdown()'s joins (#440).
     32 covers the ~16 jobs with headroom; the scheduler now logs any jobs
     still queued at teardown, so an under-provisioned cap is visible
     instead of a silent hang. */
  Base::TScheduler::TPolicy(2, 32, std::chrono::milliseconds(1000)).RunUntilCtrlC(
      [&](Base::TScheduler *scheduler) {
        int exit_code = EXIT_FAILURE;
        Orly::Server::TServer *server = nullptr;
        try {
          TIndyTestServerCmd server_cmd;
          server_cmd.MemorySim = true;
          server_cmd.Create = true;
          server_cmd.StartingState = "SOLO";
          server_cmd.InstanceName = "orlyc";
          server_cmd.PackageDirectory = cmd.OutputDir.size() > 0 ? cmd.OutputDir : Util::GetCwd();
          /* No client should ever connect; bind listeners to ephemeral ports so
             concurrent lang_test compilers never collide on a port. */
          server_cmd.PortNumber = 0;
          server_cmd.WsPortNumber = 0;
          server_cmd.SlavePortNumber = 0;
          server_cmd.ReportingPortNumber = 0;
          /* Keep this compiler-embedded server tiny and host-RAM-independent:
             every pool below is otherwise scaled up by available memory. */
          server_cmd.MemorySimMB = 32;
          server_cmd.MemorySimSlowMB = 8;
          server_cmd.PageCacheSizeMB = 8;
          server_cmd.BlockCacheSizeMB = 8;
          server_cmd.DurableCacheSize = 256;
          server_cmd.MaxRepoCacheSize = 512;
          server_cmd.NumFiberFrames = 512;
          server_cmd.NumDiskEvents = 512;
          server_cmd.NumMemMergeThreads = 1;
          server_cmd.NumDiskMergeThreads = 1;
          server_cmd.NumWsThreads = 1;
          server_cmd.DurableMappingPoolSize = 256;
          server_cmd.DurableMappingEntryPoolSize = 2000;
          server_cmd.DurableLayerPoolSize = 512;
          server_cmd.DurableMemEntryPoolSize = 5000;
          server_cmd.RepoMappingPoolSize = 512;
          server_cmd.RepoMappingEntryPoolSize = 5000;
          server_cmd.RepoDataLayerPoolSize = 512;
          server_cmd.TransactionMutationPoolSize = 500;
          server_cmd.TransactionPoolSize = 200;
          server_cmd.UpdatePoolSize = 4000;
          server_cmd.UpdateEntryPoolSize = 8000;
          server_cmd.DiskBufferBlockPoolSize = 256;
          /* Populate the hardware-derived fast/slow/merge core assignment that
             Parse() would normally fill in; the server requires non-empty
             fast/slow core vectors. */
          server_cmd.ResolveCoreVecDefaults();

          server = new Orly::Server::TServer(scheduler, server_cmd);
          /* Installing the package, opening a session, and running the tests all
             create durable objects / transactions, which must execute inside a
             fiber (TCompletionTrigger::Wait asserts on LocalFrame). RunPackageTests
             does all of that on a fast runner and hands back the result. */
          bool ok = server->RunPackageTests(output.Name.Name, output.Version, cmd.VerboseTests);
          exit_code = ok ? EXIT_SUCCESS : EXIT_FAILURE;
        } catch (const std::exception &ex) {
          std::cerr << "error: running tests on indy: " << ex.what() << std::endl;
          exit_code = EXIT_FAILURE;
        } catch (...) {
          std::cerr << "error: running tests on indy: unknown error" << std::endl;
          exit_code = EXIT_FAILURE;
        }
        /* Shutdown on every path, success or throw: the server's service
           loops park scheduler workers in blocking syscalls, and the
           scheduler only quiesces (synthesizing the ctrl-c RunUntilCtrlC
           waits for) once every worker is idle.  Skipping Shutdown() after
           an exception would therefore hang the process instead of exiting
           FAILURE (#440). */
        if (server) {
          try {
            server->Shutdown();
            delete server;
          } catch (const std::exception &ex) {
            std::cerr << "error: tearing down test server: " << ex.what() << std::endl;
            std::cout.flush();
            std::cerr.flush();
            /* Teardown is wedged or broken; a deterministic non-zero exit
               beats a hang. */
            _exit(EXIT_FAILURE);
          }
        }
        /* No "MM_NOTICE: Tests done" here: CompileCode() prints it after we
           return (it was only printed here back when this job _exit()'d and
           CompileCode's copy was unreachable); a second copy would add a
           section to the machine-form output lang_test baselines compare. */
        std::cout.flush();
        std::cerr.flush();
        /* See the pool-manager note above. */
        Orly::Indy::Disk::Util::TDiskController::TEvent::DiskEventPoolManager.release();
        result_code = exit_code;
        /* Returning quiesces the scheduler; RunUntilCtrlC then returns. */
      });

  return result_code == EXIT_SUCCESS;
}

int CompileCode(const TCompilerConfig &cmd) {

  string src = cmd.Source;
  if(src.front() != '/') {
    src = Util::GetCwd() + '/' + src;
  }

  int result = EXIT_FAILURE;
  try {
    Package::TVersionedName output;
    /* A TypeCzar must be live while we compile (it owns the type singletons /
       interners the compiler builds against). The indy test server stands up
       its own TypeCzar, and a process may hold only one, so let this one die
       before RunTestsOnIndy builds the server. */ {
      Type::TTypeCzar type_czar;
      output = Compiler::Compile(
                   Base::TPath(src),
                   cmd.OutputDir,
                   cmd.DebugOutput,
                   cmd.MachineForm,
                   cmd.SemanticOnly);
      if (cmd.SkipTests || cmd.SemanticOnly) {
        if (cmd.MachineForm) {
          cout << "MM_NOTICE: Skipped tests" << endl;
        }
        return EXIT_SUCCESS;
      }
    }
    /* Run the package's test{} blocks on the real server engine (#262). */
    if (cmd.MachineForm) {
      cout << "MM_NOTICE: Running tests" << endl;
    }
    result = RunTestsOnIndy(output, cmd) ? EXIT_SUCCESS : EXIT_FAILURE;
    if (cmd.MachineForm) {
      cout << "MM_NOTICE: Tests done" << endl;
    }
  } catch (const Compiler::TCompileFailure &ex) {
    /* Do nothing, we already printed out the error message. */
    if (cmd.DebugOutput) {
      cerr << "compile failure: " << ex.what() << endl;
    }
  } catch (const TSourceError &src_error) {
    cerr << src_error.GetPosRange() << ' ' << src_error.what() << endl;
  } catch (const exception &ex) {
    cerr << "error: " << ex.what() << endl;
  }

  return result;
}

int main(int argc, char **argv) {
  TCompilerConfig config(argc, argv);

  return CompileCode(config);
}
